### ISSUE TITLE
Reset button throws index out of range after selecting attacker

### ISSUE THREAD

**Issue by leandwo** [raysun/polysidekick#1]
If you try to reset after selecting attacker (before calculating) an Index out of range error is thrown.

### Logs
```
2020-07-05 20:16:06.087248-0700 Polytopia Sidekick[65170:1287767] Fatal error: Index out of range: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.2.25.8/swift/stdlib/public/core/ContiguousArrayBuffer.swift, line 444
```

It appears to be caused by this block of code:
https://github.com/raysun/polysidekick/blob/1d1712dfbdbf369d92744fc69b4e350ed93c3bac/Polytopia%20Sidekick/Views/CalcView.swift#L123-L128

**Comment by raysun** [comment]
Yep, that no longer repros for me, but it might be device/timing-specific. What device or simulator are you running it on?

It's a React-like issue where I'm calling .removeAll on attackers, but SwiftUI is simultaneously rendering this loop.

**Comment by raysun** [comment]
"Fixed" by reworking the code to not pass an array binding, which is awkward to support in the current SwiftUI design
