### ISSUE TITLE
troops not appearing after being selected on iphone 8

### ISSUE THREAD

**Issue by leandwo** [raysun/polysidekick#3]
Doesn't happen in simulator, but on my iphone 8 IRL, I can't see the troops after selecting them

![bug](https://user-images.githubusercontent.com/13348080/87620857-76663e80-c6d4-11ea-89d1-c6f97f5e400c.gif)

**Comment by raysun** [comment]
wut

**Comment by raysun** [comment]
Let me know if this fixes the issue on your device.

**Comment by leandwo** [comment]
@raysun it's working for me now!
